add support link on the navbar
azimuth-cloud/azimuth pull request #282
Opened 2024-08-28 15:36 UTC by thinkC

Add Support link to navbar

2024-08-28 15:58 UTC, JohnGarbutt requested changes
We need to make this link configurable via the ansible and helm chart, then get that passed all the way through please.

It should be similar to the documentation URL, except that support should be off by default please (similar to how cloud metrics is off by default).

2024-08-28 15:58 UTC, JohnGarbutt commented on ui/src/components/navigation.js
> +    const supportLink = "https://support-link.com";
This value needs to come from the Azimuth API configuration, just like we have for the documentation please.

Have a look at the links.documentation, and trace that back to here:
https://github.com/azimuth-cloud/azimuth/blob/927026313b7cd62814d20db0d5d9031ac280dc5f/api/azimuth/views.py#L292

And that comes from here (although in your case, you will want this to default to None for the support link case:
https://github.com/azimuth-cloud/azimuth/blob/927026313b7cd62814d20db0d5d9031ac280dc5f/api/azimuth/settings.py#L267

Note the helm chart has the documentation variable here:
https://github.com/azimuth-cloud/azimuth/blob/927026313b7cd62814d20db0d5d9031ac280dc5f/chart/values.yaml#L168
Which is what goes into here:
https://github.com/azimuth-cloud/azimuth/blob/927026313b7cd62814d20db0d5d9031ac280dc5f/chart/files/api/settings/02-cloud-common.yaml#L22

Then to make this usable, we need to inject that via the ansible please:
https://github.com/azimuth-cloud/ansible-collection-azimuth-ops/blob/e85686d5fb03e336797123f7fab7831bc54178cc/roles/azimuth/defaults/main.yml#L87
which goes into the helm chart values here:
https://github.com/azimuth-cloud/ansible-collection-azimuth-ops/blob/e85686d5fb03e336797123f7fab7831bc54178cc/roles/azimuth/defaults/main.yml#L376

2024-08-28 15:58 UTC, JohnGarbutt commented on ui/src/components/navigation.js
> +                {/* add support link here */}
I think we can remove these comments and extra blank lines, please align the indentation with the other links above please.

2024-08-28 16:03 UTC, thinkC commented on ui/src/components/navigation.js
> +                {/* add support link here */}
Okay, thanks will make the changes

2024-09-19 11:04 UTC, mkjpryor requested changes
Just a handful of minor changes.

Please also rebase the PR onto the current `master`.

2024-09-19 11:04 UTC, mkjpryor commented on api/azimuth/settings.py
> +    SUPPORT_URL = Setting(default = "https://confluence.skatelescope.org/display/SRCSC/Azimuth+Support+on+Cambridge+Arcus")
The default here should be `None`, as in the commented out line above. The SKA Confluence link should be in the Arcus Azimuth config only.

2024-09-19 11:04 UTC, mkjpryor commented on ui/src/components/navigation.js
> +    console.log(links);
Please remove debugging statements

2024-09-19 11:04 UTC, mkjpryor commented on ui/src/components/navigation.js
> +
Remove whitespace for consistency with the rest of the code

2024-09-19 11:04 UTC, mkjpryor commented on ui/src/components/navigation.js
> +
Same here please

2024-11-06 10:05 UTC, thinkC commented
Hello @mkjpryor , @JohnGarbutt . Update made. Please review

2024-11-06 10:12 UTC, JohnGarbutt reviewed
Thank you Tunde. This looks good to me. Will leave @mkjpryor to confirm he is happy now.

2024-11-12 11:38 UTC, mkjpryor approved these changes
LGTM

2024-11-12 11:38 UTC, merged